from . import document_custom
from . import doc_tag_master
from . import res_patner
from . import product
from . import sale_order
from . import stock_picking
from . import sale_order_document_line
from . import res_config_setting
from . import student_activity